### ISSUE TITLE
Advance hardware integration

### ISSUE THREAD

**Issue by ekateriniioannou** [QualiMaster/qm-issues#52] opened 2015-10-23 10:18 UTC
- Related work has started (interrupted due to QM evaluations) 
- Finish development and test

**Comment by eichelbe** [comment] 2015-10-29 11:27
This seems to be a duplicate of #7. Will close this issue, and if it is not a duplicate, please re-open and explain ;)

**Closed as completed by eichelbe** 2015-10-29 11:27 UTC
Labels: hardware
